[default]
extend-ignore-re = [
	"(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
	"(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
	"(#|//)\\s*spellchecker:ignore-next-line\\n.*",
	"(?i)#\\s*typos:ignore\\s+\\w+",
	"(?i)//\\s*typos:ignore\\s+\\w+",
	"(?Rm)^.*(#|//)\\s*typos:ignore$",
]


[default.extend-words]
pacakge = "pacakge"

[files]
extend-exclude = ["**/gui.py"]


