name: Build and Package with Nuitka
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"
          cache: "pip"

      - name: Set Up UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/pyproject.toml

      - name: Install Dependencies with uv
        run: |
          uv pip install --system -r ./Aumiao-py/project/requirements.txt
          uv pip install --system nuitka

      - name: Cache UPX
        id: cache-upx
        uses: actions/cache@v4
        with:
          path: upx.exe
          key: upx-4.2.4-win64

      - name: Download and Install UPX
        if: steps.cache-upx.outputs.cache-hit != 'true'
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip" -OutFile "upx.zip"
          Expand-Archive -Path "upx.zip" -DestinationPath "upx"
          Move-Item -Path "upx\upx-4.2.4-win64\upx.exe" -Destination "upx.exe"

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone `
            --main="./Aumiao-py/main.py" `
            --company-name="Aumiao Team" `
            --product-name="Aumiao" `
            --file-version="2.0.0" `
            --product-version="2.0.0" `
            --file-description="A Codemao Community Tool" `
            --follow-imports `
            --copyright="Copyright © 2025 喵鱼a. All rights reserved." `
            --output-filename="Aumiao" `
            --windows-icon-from-ico="./Aumiao-py/project/favicon.ico" `
            --remove-output `
            --output-dir="./build" `
            --lto=yes `
            --enable-plugin=upx `
            --jobs=4 `
            --upx-binary="./upx/upx-4.2.4-win64/upx.exe" `
            --assume-yes-for-downloads

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aumiao-${{ github.sha }}-win64
          path: build/**
          if-no-files-found: error
          retention-days: 5
# python -m nuitka --standalone --main="main.py" --company-name="Aumiao Team" --product-name="Aumiao" --file-version="2.0.0" --product-version="2.0.0" --file-description="A Codemao Community Tool" --follow-imports --copyright="Copyright © 2025 喵鱼a. All rights reserved. " --output-filename="Aumiao" --windows-icon-from-ico="./project/favicon.ico" --remove-output --output-dir="./build" --lto=yes --enable-plugin=upx --jobs=4 --upx-binary=d:\upx\upx.exe --msvc=latest
