name: Build and Package with Nuitka

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"
  UPX_VERSION: "4.2.4"
  BUILD_TYPE: Release
  PROJECT_DIR: "Aumiao-py" # 新增项目目录变量

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }} # 全局工作目录设置

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.PROJECT_DIR }} # 明确检出到子目录

      - name: Setup Beijing Timezone
        shell: bash
        run: |
          echo "BUILD_DATE=$(TZ=Asia/Shanghai date +'%y%m%d')" >> $GITHUB_ENV
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +'%H%M%S')" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: "x64"
          cache: "pip"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PROJECT_DIR }}/.venv
            ~/.cache/pip
            ~/.cache/uv
            upx.exe
          key: ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('${{ env.PROJECT_DIR }}/**/requirements.txt') }}-upx-${{ env.UPX_VERSION }}
          restore-keys: |
            ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-

      - name: Install 7-Zip
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2409-x64.msi" -OutFile "7z-installer.msi"
          Start-Process msiexec.exe -ArgumentList "/i 7z-installer.msi /quiet" -Wait
          $sevenZipPath = "C:\Program Files\7-Zip"
          if (Test-Path $sevenZipPath) {
              "$sevenZipPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
              $env:PATH += ";$sevenZipPath"
          } else {
              Write-Error "7-Zip installation failed!"
              exit 1
          }

      # - name: Validate project structure
      #   shell: pwsh
      #   working-directory: ${{ env.PROJECT_DIR }}
      #   run: |
      #     # 验证关键文件路径
      #     $requiredFiles = @(
      #         "pyproject.toml",
      #         "requirements.txt",
      #         "src/project/favicon.ico"
      #     )

      #     foreach ($file in $requiredFiles) {
      #         if (-not (Test-Path $file)) {
      #             Write-Error "Missing required file: $file"
      #             Get-ChildItem -Recurse -Depth 3  # 打印目录结构用于调试
      #             exit 1
      #         }
      #     }

      - name: Setup Python Environment
        shell: pwsh
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip uv
          uv sync
          uv pip list

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          assume-yes-for-downloads: true
          company-name: "Aumiao Team"
          copyright: "Copyright © 2025 喵鱼a. All rights reserved."
          file-version: "2.0.0"
          follow-imports: true
          jobs: 4
          lto: "yes"
          mode: standalone
          output-dir: ../build # 输出到仓库根目录
          output-filename: aumiao
          product-name: "Aumiao"
          product-version: "2.0.0"
          script-name: ./main.py # 相对项目目录路径
          show-progress: true
          windows-console-mode: force
          windows-icon-from-ico: "./src/project/favicon.ico" # 相对项目目录路径

      - name: Prepare Distribution
        shell: pwsh
        run: |
          $distDir = "../build/main.dist"  # 指向仓库根目录
          New-Item -Path $distDir -ItemType Directory -Force

          $essentialFiles = @(
              "./README.txt",
              "./DISCLAIMER.txt",
              "./data"
          )
          Copy-Item -Path $essentialFiles -Destination $distDir -Recurse -Force

          $versionInfo = @{
              Version   = "2.0.0"
              BuildDate = "${{ env.BUILD_DATE }}"
              GitCommit = "${{ env.GIT_SHA }}"
          } | ConvertTo-Json
          Set-Content -Path "$distDir/version.json" -Value $versionInfo

      - name: Optimize Binaries
        shell: pwsh
        continue-on-error: true
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if (-not (Test-Path "./upx.exe")) {
              $ProgressPreference = 'SilentlyContinue'
              Invoke-WebRequest "https://github.com/upx/upx/releases/download/v${{ env.UPX_VERSION }}/upx-${{ env.UPX_VERSION }}-win64.zip" -OutFile upx.zip
              Expand-Archive upx.zip -DestinationPath upx_tmp
              Move-Item upx_tmp/upx*/upx.exe . -ErrorAction SilentlyContinue
              Remove-Item upx_tmp, upx.zip -Recurse -Force
          }

          $ErrorActionPreference = 'Continue'
          ./upx.exe --best --lzma ../build/main.dist/aumiao.exe 2>&1 | Tee-Object -FilePath "../build/upx-main.log"
          Get-ChildItem ../build/main.dist/*.dll | ForEach-Object {
              ./upx.exe --best --lzma $_.FullName 2>&1 | Tee-Object -FilePath "../build/upx-dll.log" -Append
          }

      - name: Package Artifacts
        shell: pwsh
        run: |
          $packageName = "Aumiao_v2.0.0.${{ env.BUILD_DATE }}.zip"
          $distDir = Resolve-Path "../build/main.dist"
          7z a -tzip "$(Resolve-Path "../build")/$packageName" "$distDir\*"

      - name: Upload Release Package
        uses: actions/upload-artifact@v4
        with:
          name: Aumiao_v2.0.0.${{ env.BUILD_DATE }}
          path: ../build/*.zip # 指向仓库根目录
          retention-days: 7

      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build_Debug_${{ env.BUILD_DATE }}
          path: |
            ../build/**/*.log
            ../build/**/*.json
            **/nuitka-*.log
            **/nuitka-*.xml
          if-no-files-found: ignore
          retention-days: 14
