name: Build and Package with Nuitka

permissions:
  contents: write
  actions: write

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
      - "Aumiao-py/pyproject.toml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
      - "Aumiao-py/pyproject.toml"
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  COMMIT_INTERVAL: 20
  PYTHON_VERSION: "3.13"
  UPX_VERSION: "4.2.4"
  UV_VERSION: "0.4.22"

jobs:
  # 检查是否需要创建release
  check-release:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check-commits.outputs.should_release }}
      release_tag: ${{ steps.check-commits.outputs.release_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Commit Count and Create Release
        id: check-commits
        run: |
          # 获取所有tag，如果没有tag则使用初始commit
          if git describe --tags --abbrev=0 > /dev/null 2>&1; then
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "Latest tag: $LATEST_TAG"
            COMMIT_COUNT=$(git rev-list --count $LATEST_TAG..HEAD)
          else
            echo "No tags found, counting all commits"
            LATEST_TAG="initial"
            COMMIT_COUNT=$(git rev-list --count HEAD)
          fi
          
          echo "Commits since last tag: $COMMIT_COUNT"
          
          # 检查是否达到commit间隔
          if [ $COMMIT_COUNT -ge ${{ env.COMMIT_INTERVAL }} ]; then
            echo "Reached $COMMIT_COUNT commits, triggering release"
            echo "should_release=true" >> $GITHUB_OUTPUT
            
            # 生成新的版本标签 (基于时间戳)
            RELEASE_TAG="v$(date +'%Y%m%d.%H%M%S')"
            echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
            
            # 创建git tag
            git tag $RELEASE_TAG
            git push origin $RELEASE_TAG
          else
            echo "Only $COMMIT_COUNT commits, skipping release (needs ${{ env.COMMIT_INTERVAL }})"
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "release_tag=" >> $GITHUB_OUTPUT
          fi

  # 生成变更日志
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: check-release
    if: needs.check-release.outputs.should_release == 'true'
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog with git-cliff
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: ./Aumiao-py/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md

      - name: Save changelog to file
        run: |
          echo "${{ steps.git-cliff.outputs.content }}" > CHANGES.md
          cat CHANGES.md

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGES.md
          retention-days: 1

  build:
    permissions:
      contents: read
      actions: write
    runs-on: windows-latest
    timeout-minutes: 30
    needs: [check-release, changelog]
    
    env:
      UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Beijing Timezone
        shell: bash
        run: |
          echo "BUILD_DATE=$(TZ=Asia/Shanghai date +'%y%m%d')" >> $GITHUB_ENV
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +'%H%M%S')" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "SHOULD_RELEASE=${{ needs.check-release.outputs.should_release }}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{ needs.check-release.outputs.release_tag }}" >> $GITHUB_ENV

      - name: Read Project Version
        id: version
        shell: pwsh
        run: |
          $tomlContent = Get-Content -Path ./Aumiao-py/pyproject.toml -Raw -Encoding UTF8
          Write-Host "TOML content: $tomlContent"

          $versionLine = $tomlContent | Select-String -Pattern 'version\s*=\s*"([\d.]+)"'
          if ($versionLine) {
              $version = $versionLine.Matches.Groups[1].Value
              Write-Host "Extracted version: $version"
              Write-Output "PROJECT_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          } else {
              Write-Error "Version not found in pyproject.toml"
              exit 1
          }

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          cache-dependency-glob: |
            Aumiao-py/pyproject.toml
            Aumiao-py/uv.lock

      - name: Set up Python with uv
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Cache Build Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.UV_CACHE_DIR }}
            upx.exe
          key: ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-uv-${{ env.UV_VERSION }}-${{ hashFiles('Aumiao-py/pyproject.toml', 'Aumiao-py/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-uv-${{ env.UV_VERSION }}-

      - name: Install 7-Zip and Inno Setup
        shell: pwsh
        run: |
          # 安装7-Zip
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2409-x64.msi" -OutFile "7z-installer.msi"
          Start-Process msiexec.exe -ArgumentList "/i 7z-installer.msi /quiet" -Wait
          $sevenZipPath = "C:\Program Files\7-Zip"
          if (Test-Path $sevenZipPath) {
              "$sevenZipPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          }

          # 安装 Inno Setup
          Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.5.0.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART" -Wait
          $innoPath = "C:\Program Files (x86)\Inno Setup 6"
          if (Test-Path $innoPath) {
              "$innoPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
          }
          Remove-Item "innosetup.exe" -Force

      - name: Install Project Dependencies with uv
        working-directory: ./Aumiao-py
        run: |
          uv sync --locked --all-extras --dev

      - name: Build with Nuitka using uv
        working-directory: ./Aumiao-py
        run: |
          uv run nuitka \
            --assume-yes-for-downloads \
            --company-name="Aumiao Team" \
            --copyright="Copyright © 2025 喵鱼a. All rights reserved." \
            --file-version="${{ env.PROJECT_VERSION || '2.0.0' }}" \
            --follow-imports \
            --jobs=4 \
            --lto=yes \
            --mode=standalone \
            --output-dir=../build \
            --output-filename=aumiao \
            --product-name="Aumiao" \
            --product-version="${{ env.PROJECT_VERSION || '2.0.0' }}" \
            --show-progress \
            --windows-console-mode=force \
            --windows-icon-from-ico="./resource/icons/favicon.ico" \
            ./main.py

      - name: Run recover.py with uv
        working-directory: ./Aumiao-py
        run: uv run python recover.py

      - name: Prepare Distribution
        shell: pwsh
        run: |
          $distDir = "build/main.dist"
          New-Item -Path "$distDir/.log" -ItemType Directory -Force
          $essentialFiles = @(
              "./Aumiao-py/README.txt",
              "./Aumiao-py/DISCLAIMER.txt",
              "./Aumiao-py/data"
          )
          Copy-Item -Path $essentialFiles -Destination $distDir -Recurse -Force
          $versionInfo = @{
              Version   = "${{ env.PROJECT_VERSION || '2.0.0' }}"
              BuildDate = "${{ env.BUILD_DATE }}"
              GitCommit = "${{ env.GIT_SHA }}"
              ReleaseTag = "${{ env.RELEASE_TAG }}"
          } | ConvertTo-Json
          Set-Content -Path "$distDir/version.json" -Value $versionInfo

      - name: Optimize Binaries
        shell: pwsh
        continue-on-error: true
        run: |
          if (-not (Test-Path "./upx.exe")) {
              $ProgressPreference = 'SilentlyContinue'
              Invoke-WebRequest "https://github.com/upx/upx/releases/download/v${{ env.UPX_VERSION }}/upx-${{ env.UPX_VERSION }}-win64.zip" -OutFile upx.zip
              Expand-Archive upx.zip -DestinationPath upx_tmp
              Move-Item upx_tmp/upx*/upx.exe . -ErrorAction SilentlyContinue
              Remove-Item upx_tmp, upx.zip -Recurse -Force
          }

          ./upx.exe --best --lzma ./build/main.dist/aumiao.exe 2>&1 | Tee-Object -FilePath "$pwd/build/upx-main.log" || Write-Host "UPX compression warning (ignored)"

          $excludeDlls = @("vcruntime140.dll", "vcruntime140_1.dll")
          Get-ChildItem ./build/main.dist/*.dll | Where-Object { 
              $_.Name -notin $excludeDlls 
          } | ForEach-Object {
              ./upx.exe --best --lzma $_.FullName 2>&1 | Tee-Object -FilePath "$pwd/build/upx-dll.log" -Append
          }

      - name: Build Installer with Inno Setup
        shell: pwsh
        run: ISCC.exe ./Aumiao-py/resource/aumiao.iss

      - name: Package Artifacts
        shell: pwsh
        run: |
          $packageName = "Aumiao_v${{ env.PROJECT_VERSION || '2.0.0' }}.${{ env.BUILD_DATE }}_alpha.zip"
          $distDir = Resolve-Path "./build/main.dist"
          7z a -tzip "$(Resolve-Path "./build")/$packageName" "$distDir\*"

      - name: Minimize uv cache (CI optimization)
        run: uv cache prune --ci

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aumiao_Build_${{ env.BUILD_DATE }}
          path: |
            build/*.zip
            build/installer/*.exe
          retention-days: 7

      - name: Create GitHub Release
        if: env.SHOULD_RELEASE == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Aumiao ${{ env.RELEASE_TAG }}"
          body: ${{ needs.changelog.outputs.release_body }}
          files: |
            build/installer/*.exe
            build/*.zip
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build_Debug_${{ env.BUILD_DATE }}
          path: |
            build/**/*.log
            build/**/*.json
            **/nuitka-*.log
            **/nuitka-*.xml
          if-no-files-found: ignore
          retention-days: 14