name: Build and Package with Nuitka

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"
  UPX_VERSION: "4.2.4"
  BUILD_TYPE: Release
  PROJECT_DIR: "Aumiao-py"

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.PROJECT_DIR }}

      - name: Setup Beijing Timezone
        shell: bash
        run: |
          echo "BUILD_DATE=$(TZ=Asia/Shanghai date +'%y%m%d')" >> $GITHUB_ENV
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date +'%H%M%S')" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: "x64"
          cache: "pip"

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PROJECT_DIR }}/.venv
            ~/.cache/pip
            ~/.cache/uv
            upx.exe
          key: ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-${{ hashFiles('${{ env.PROJECT_DIR }}/**/requirements.txt') }}-upx-${{ env.UPX_VERSION }}
          restore-keys: |
            ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-

      - name: Install 7-Zip
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2409-x64.msi" -OutFile "7z-installer.msi"
          Start-Process msiexec.exe -ArgumentList "/i 7z-installer.msi /quiet" -Wait
          $sevenZipPath = "C:\Program Files\7-Zip"
          if (Test-Path $sevenZipPath) {
              "$sevenZipPath" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8
              $env:PATH += ";$sevenZipPath"
          } else {
              Write-Error "7-Zip installation failed!"
              exit 1
          }

      - name: Setup Python Environment
        shell: pwsh
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          python -m pip install --upgrade pip uv
          uv sync
          uv add requests
          uv pip list

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          assume-yes-for-downloads: true
          company-name: "Aumiao Team"
          copyright: "Copyright © 2025 喵鱼a. All rights reserved."
          file-version: "2.0.0"
          follow-imports: true
          jobs: 4
          lto: "yes"
          mode: standalone
          output-dir: build  # 修复路径，不再使用../
          output-filename: aumiao
          product-name: "Aumiao"
          product-version: "2.0.0"
          script-name: ./main.py  # 根据工作目录调整路径
          show-progress: true
          windows-console-mode: force
          windows-icon-from-ico: "src/project/favicon.ico"  # 确保路径正确
        env:
          NUITKA_CACHE_DIR: ${{ github.workspace }}/nuitka/cache

      - name: Prepare Distribution
        shell: pwsh
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          $distDir = "build/main.dist"  # 使用相对当前目录的路径
          New-Item -Path $distDir -ItemType Directory -Force
          Copy-Item -Path README.txt, DISCLAIMER.txt, data -Destination $distDir -Recurse -Force
          $versionInfo = @{
              Version   = "2.0.0"
              BuildDate = "${{ env.BUILD_DATE }}"
              GitCommit = "${{ env.GIT_SHA }}"
          } | ConvertTo-Json
          Set-Content -Path "$distDir/version.json" -Value $versionInfo

      - name: Optimize Binaries
        shell: pwsh
        continue-on-error: true
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          if (-not (Test-Path "./upx.exe")) {
              $ProgressPreference = 'SilentlyContinue'
              Invoke-WebRequest "https://github.com/upx/upx/releases/download/v${{ env.UPX_VERSION }}/upx-${{ env.UPX_VERSION }}-win64.zip" -OutFile upx.zip
              Expand-Archive upx.zip -DestinationPath upx_tmp
              Move-Item upx_tmp/upx*/upx.exe . -ErrorAction SilentlyContinue
              Remove-Item upx_tmp, upx.zip -Recurse -Force
          }
          ./upx.exe --best --lzma build/main.dist/aumiao.exe 2>&1 | Tee-Object -FilePath "build/upx-main.log"
          Get-ChildItem build/main.dist/*.dll | ForEach-Object {
              ./upx.exe --best --lzma $_.FullName 2>&1 | Tee-Object -FilePath "build/upx-dll.log" -Append
          }

      - name: Package Artifacts
        shell: pwsh
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          $packageName = "Aumiao_v2.0.0.${{ env.BUILD_DATE }}.zip"
          $distDir = Resolve-Path "build/main.dist"
          7z a -tzip "build/$packageName" "$distDir\*"

      - name: Upload Release Package
        uses: actions/upload-artifact@v4
        with:
          name: Aumiao_v2.0.0.${{ env.BUILD_DATE }}
          path: ${{ env.PROJECT_DIR }}/build/*.zip
          retention-days: 7

      - name: Upload Debug Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build_Debug_${{ env.BUILD_DATE }}
          path: |
            ${{ env.PROJECT_DIR }}/build/**/*.log
            ${{ env.PROJECT_DIR }}/build/**/*.json
            ${{ env.PROJECT_DIR }}/**/nuitka-*.log
            ${{ env.PROJECT_DIR }}/**/nuitka-*.xml
          if-no-files-found: ignore
          retention-days: 14
