name: Code Quality Automation

on:
  pull_request:
  pull_request_target:

jobs:
  code-styling:
    name: "Lint & Format"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Checkout the PR branch directly

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --fix --preview --output-format=github"
          src: "./Aumiao-py/src"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format"
          src: "./Aumiao-py/src"

  spell-check:
    name: "Spell Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Checkout the PR branch

      - name: Validate Spelling
        uses: crate-ci/typos@v1.30.1
        with:
          config: ./Aumiao-py/typos.toml
          files: ./Aumiao-py/src

  apply-fixes:
    name: "Apply Fixes"
    needs: [code-styling, spell-check]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Changes from Previous Jobs
        uses: actions/download-artifact@v4
        with:
          name: code-fixes
          path: ./Aumiao-py/src

      - name: Detect Modifications
        id: changes
        run: |
          git diff --quiet || echo "HAS_CHANGES=true" >> $GITHUB_ENV

      - name: Commit Fixes
        if: env.HAS_CHANGES == 'true'
        run: |
          git config user.name "Code Quality Bot"
          git config user.email "bot@aumiao-py"
          git add -A
          git commit -m "style: Automated code quality fixes"
          git push origin HEAD:${{ github.head_ref }}
