name: Code Quality Automation

# 添加最小权限声明
permissions:
  contents: read  # 默认只读权限
  pull-requests: write  # 需要写权限推送修复

on:
  pull_request:
  pull_request_target:

jobs:
  code-styling:
    # 显式声明作业权限（继承全局）
    permissions:
      contents: read
    name: "Lint & Format"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --fix --preview --output-format=github"
          src: "./Aumiao-py/src"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format"
          src: "./Aumiao-py/src"

  spell-check:
    permissions:
      contents: read
    name: "Spell Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Spelling
        uses: crate-ci/typos@v1.30.1
        with:
          config: ./Aumiao-py/typos.toml
          files: ./Aumiao-py/src

  apply-fixes:
    # 此作业需要写权限
    permissions:
      contents: write
      pull-requests: write
    name: "Apply Fixes"
    needs: [code-styling, spell-check]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # 安全修复：使用受信任的checkout方式
      - name: Checkout Code (Safe)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # 直接使用提交SHA
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect Modifications
        id: changes
        run: |
          git status --porcelain | grep -q . && echo "HAS_CHANGES=true" >> $GITHUB_ENV || echo "HAS_CHANGES=false" >> $GITHUB_ENV

      - name: Commit Fixes
        if: env.HAS_CHANGES == 'true'
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          git config --global user.name "Code Quality Bot"
          git config --global user.email "bot@aumiao-py"
          git add -A
          git commit -m "style: Automated code quality fixes"
          git push origin HEAD:$HEAD_REF