name: Code Quality Automation

on:
  pull_request:
  pull_request_target:

jobs:
  code-styling:
    name: "Lint & Format"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --fix --output-format=github ./Aumiao-py/src"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format -- --output-format=github ./Aumiao-py/src"

  spell-check:
    name: "Spell Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Spelling
        uses: crate-ci/typos@v1.30.1
        with:
          config: ./Aumiao-py/typos.toml
          files: ./Aumiao-py/src

  apply-fixes:
    name: "Apply Fixes"
    needs: [ code-styling, spell-check ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect Modifications
        id: changes
        run: |
          git status --porcelain | grep -q . && echo "HAS_CHANGES=true" >> $GITHUB_ENV || echo "HAS_CHANGES=false" >> $GITHUB_ENV

      - name: Commit Fixes
        if: env.HAS_CHANGES == 'true'
        run: |
          git config --global user.name "Code Quality Bot"
          git config --global user.email "bot@aumiao-py"
          git add -A
          git commit -m "style: Automated code quality fixes"
          git push origin HEAD:${{ github.head_ref }}