name: Code Quality Automation

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
      - "Aumiao-py/pyproject.toml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "Aumiao-py/src/**/*.py"
      - "Aumiao-py/pyproject.toml"
  workflow_dispatch:

jobs:
  code-styling:
    name: "Lint & Format"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check --fix --preview --output-format=github"
          src: "./Aumiao-py/src"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format"
          src: "./Aumiao-py/src"

      - name: Upload Ruff Fixes
        uses: actions/upload-artifact@v4
        with:
          name: code-fixes
          path: ./Aumiao-py/src
          retention-days: 1

  spell-check:
    name: "Spell Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Validate Spelling
        uses: crate-ci/typos@v1.30.1
        with:
          config: ./Aumiao-py/typos.toml
          files: ./Aumiao-py/src

      - name: Upload Spell Fixes
        uses: actions/upload-artifact@v4
        with:
          name: spell-fixes
          path: ./Aumiao-py/src
          retention-days: 1

  apply-fixes:
    name: "Apply Fixes"
    if: github.event.pull_request.head.repo.full_name == github.repository
    needs: [code-styling, spell-check]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Changes from Previous Jobs
        uses: actions/download-artifact@v4
        with:
          name: code-fixes
          path: ./Aumiao-py/src
          merge-multiple: true

      - name: Detect Modifications
        id: changes
        run: |
          git diff --quiet || echo "HAS_CHANGES=true" >> $GITHUB_ENV

      - name: Commit Fixes
        if: env.HAS_CHANGES == 'true'
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          git config user.name "Code Quality Bot"
          git config user.email "bot@aumiao-py"
          git add -A
          git commit -m "style: Automated code quality fixes"
          git push origin HEAD:$BRANCH_NAME
