name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint_format:
    timeout-minutes: 10
    name: "Lint and Format"
    runs-on: ubuntu-latest
    steps:
      - name: "Check Out"
        uses: actions/checkout@v4

      - name: "Lint"
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --fix"
          changed-files: "true"

      - name: "Format"
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: "true"
          args: "format"

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "${{ env.PYTHON_VERSION }}"

      # - name: "Install uv"
      #   uses: astral-sh/setup-uv@v4

      # - name: "Python format"
      #   run: uvx ruff format --diff . --exclude video

      # - name: "Python lint"
      #   run: uvx ruff check . --exclude video

      # - name: "Python type check"
      #   run: uvx mypy

  typos:
    timeout-minutes: 10
    name: "Code Spell Checker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: .
